"use client";

import { useEffect, useState } from "react";

import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  CoursesTable,
  WorkspaceTableCell,
  WorkspaceTableFrame,
  WorkspaceTableHeader,
  WorkspaceTableHeaderCell,
  WorkspaceTableRow,
} from "@/components/workspace/shared/courses-table";
import {
  getGroupedAssessmentItemPrefix,
  normalizeDropLowest,
  resizeGroupedAssessmentItems,
} from "@/lib/assessments/grouped-assessment-utils";
import {
  sanitizeIntegerInput,
  sanitizePlainNumberInput,
  sanitizeScoreExpressionInput,
} from "@/lib/assessments/numeric-input";
import {
  GroupedAssessment,
  GroupedAssessmentCategory,
  GroupedAssessmentItem,
} from "@/lib/shared/types";

interface GroupedAssessmentEditorProps {
  category: GroupedAssessmentCategory;
  value: {
    name: string;
    weight: string;
    itemCount: number;
    dropLowest: number;
    items: GroupedAssessmentItem[];
  };
  onChange: (nextValue: GroupedAssessmentEditorProps["value"]) => void;
}

export function GroupedAssessmentEditor({
  category,
  value,
  onChange,
}: GroupedAssessmentEditorProps) {
  const dropLowest = normalizeDropLowest(value.dropLowest, value.itemCount);
  const [itemCountDraft, setItemCountDraft] = useState(String(value.itemCount));
  const [dropLowestDraft, setDropLowestDraft] = useState(String(dropLowest));

  useEffect(() => {
    setItemCountDraft(String(value.itemCount));
  }, [value.itemCount]);

  useEffect(() => {
    setDropLowestDraft(String(dropLowest));
  }, [dropLowest]);

  function update(updates: Partial<GroupedAssessmentEditorProps["value"]>) {
    onChange({
      ...value,
      ...updates,
    });
  }

  function updateItem(itemId: string, updates: Partial<GroupedAssessmentItem>) {
    update({
      items: value.items.map((item) =>
        item.id === itemId ? { ...item, ...updates } : item,
      ),
    });
  }

  function isAutoGeneratedLabel(label: string, name: string, index: number) {
    return (
      label.trim() === `${getGroupedAssessmentItemPrefix(name)} ${index + 1}`
    );
  }

  function updateCategoryName(nextName: string) {
    const relabeledItems = value.items.map((item, index) => {
      if (!isAutoGeneratedLabel(item.label, value.name, index)) {
        return item;
      }

      return {
        ...item,
        label: `${getGroupedAssessmentItemPrefix(nextName)} ${index + 1}`,
      };
    });

    update({
      name: nextName,
      items: relabeledItems,
    });
  }

  function commitItemCount(rawValue: string) {
    const nextCount = Math.max(Number(rawValue) || 1, 1);
    const nextItems = resizeGroupedAssessmentItems(
      category,
      nextCount,
      value.name,
      value.items,
    );
    const nextDropLowest = normalizeDropLowest(
      value.dropLowest,
      nextItems.length,
    );

    update({
      itemCount: nextItems.length,
      items: nextItems,
      dropLowest: nextDropLowest,
    });

    setItemCountDraft(String(nextItems.length));
    setDropLowestDraft(String(nextDropLowest));
  }

  function commitDropLowest(rawValue: string) {
    const nextDropLowest = normalizeDropLowest(
      Number(rawValue),
      value.itemCount,
    );
    update({
      dropLowest: nextDropLowest,
    });
    setDropLowestDraft(String(nextDropLowest));
  }

  return (
    <div className="flex min-h-0 max-w-[760px] flex-1 flex-col gap-5 sm:gap-6">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4">
        <div className="space-y-2">
          <Label htmlFor={`${category}-name`}>Category name *</Label>
          <Input
            className="text-center"
            id={`${category}-name`}
            onChange={(event) => updateCategoryName(event.target.value)}
            placeholder="e.g. Tutorials, quizzes"
            value={value.name}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor={`${category}-weight`}>Total weight (%) *</Label>
          <Input
            className="text-center"
            id={`${category}-weight`}
            min={0}
            onChange={(event) =>
              update({ weight: sanitizePlainNumberInput(event.target.value) })
            }
            inputMode="decimal"
            type="text"
            value={value.weight}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor={`${category}-count`}>Number of items *</Label>
          <Input
            className="text-center"
            id={`${category}-count`}
            inputMode="numeric"
            onBlur={() => commitItemCount(itemCountDraft)}
            onChange={(event) =>
              setItemCountDraft(sanitizeIntegerInput(event.target.value))
            }
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                event.currentTarget.blur();
              }
              if (event.key === "Escape") {
                setItemCountDraft(String(value.itemCount));
                event.currentTarget.blur();
              }
            }}
            type="text"
            value={itemCountDraft}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor={`${category}-drop`}>Drop lowest</Label>
          <Input
            className="text-center"
            id={`${category}-drop`}
            inputMode="numeric"
            onBlur={() => commitDropLowest(dropLowestDraft)}
            onChange={(event) =>
              setDropLowestDraft(sanitizeIntegerInput(event.target.value))
            }
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                event.currentTarget.blur();
              }
              if (event.key === "Escape") {
                setDropLowestDraft(String(dropLowest));
                event.currentTarget.blur();
              }
            }}
            type="text"
            value={dropLowestDraft}
          />
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col space-y-3">
        <div className="text-center">
          <p className="text-sm font-semibold text-foreground">
            {value.name.trim()
              ? `${value.name.trim()} items`
              : "Category items"}
          </p>
          <p className="text-sm text-ink-soft">
            Rename items and capture marks directly in the table.
          </p>
        </div>

        <div className="min-h-0 sm:hidden">
          <div className="max-h-[34vh] overflow-auto rounded-[18px] border border-white/24 bg-white/34 backdrop-blur-sm dark:border-white/10 dark:bg-white/5">
            <div className="grid grid-cols-[minmax(0,1fr)_92px] border-b border-white/18 bg-white/36 px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-ink-soft dark:border-white/8 dark:bg-white/6">
              <span>Item</span>
              <span className="text-right">Grade</span>
            </div>
            {value.items.map((item) => (
              <div
                className="grid grid-cols-[minmax(0,1fr)_92px] items-center gap-3 border-t border-line px-4 py-3 first:border-t-0"
                key={item.id}
              >
                <Input
                  className="text-left"
                  id={`${category}-label-${item.id}`}
                  onChange={(event) =>
                    updateItem(item.id, { label: event.target.value })
                  }
                  variant="inline-heading"
                  value={item.label}
                />
                <GroupedScoreInput
                  id={`${category}-score-${item.id}`}
                  onCommit={(scoreAchieved) =>
                    updateItem(item.id, {
                      scoreAchieved,
                      totalPossible: 100,
                    })
                  }
                  value={item.scoreAchieved}
                />
              </div>
            ))}
          </div>
        </div>

        <WorkspaceTableFrame className="mx-auto hidden max-h-[48vh] w-fit max-w-full rounded-[20px] sm:inline-block">
          <CoursesTable className="w-auto min-w-[440px] table-auto">
            <WorkspaceTableHeader className="text-[11px] tracking-[0.14em]">
              <tr>
                <WorkspaceTableHeaderCell className="w-[280px] py-2.5 text-center lg:px-5 lg:py-3">
                  Item
                </WorkspaceTableHeaderCell>
                <WorkspaceTableHeaderCell className="w-[120px] py-2.5 text-center lg:px-5 lg:py-3">
                  Mark
                </WorkspaceTableHeaderCell>
              </tr>
            </WorkspaceTableHeader>
            <tbody>
              {value.items.map((item) => (
                <WorkspaceTableRow key={item.id}>
                  <WorkspaceTableCell className="py-2.5 lg:px-5 lg:py-3">
                    <Input
                      className="text-center"
                      id={`${category}-label-${item.id}`}
                      onChange={(event) =>
                        updateItem(item.id, { label: event.target.value })
                      }
                      variant="inline"
                      value={item.label}
                    />
                  </WorkspaceTableCell>
                  <WorkspaceTableCell className="py-2.5 text-center lg:px-5 lg:py-3">
                    <GroupedScoreInput
                      id={`${category}-score-${item.id}`}
                      onCommit={(scoreAchieved) =>
                        updateItem(item.id, {
                          scoreAchieved,
                          totalPossible: 100,
                        })
                      }
                      value={item.scoreAchieved}
                    />
                  </WorkspaceTableCell>
                </WorkspaceTableRow>
              ))}
            </tbody>
          </CoursesTable>
        </WorkspaceTableFrame>
      </div>
    </div>
  );
}

export function getGroupedAssessmentEditorValue(assessment: GroupedAssessment) {
  return {
    name: assessment.name,
    weight: String(assessment.weight),
    itemCount: assessment.items.length,
    dropLowest: assessment.dropLowest,
    items: assessment.items,
  };
}

function GroupedScoreInput({
  id,
  value,
  onCommit,
}: {
  id: string;
  value: number | null;
  onCommit: (value: number | null) => void;
}) {
  const [draft, setDraft] = useState(formatGroupedScoreInput(value));

  useEffect(() => {
    setDraft(formatGroupedScoreInput(value));
  }, [value]);

  return (
    <div className="relative ml-auto w-[88px] sm:mx-auto">
      <Input
        className="pr-5 text-center"
        id={id}
        inputMode="decimal"
        onBlur={() => {
          const parsed = parseGroupedScoreInput(draft);
          setDraft(formatGroupedScoreInput(parsed));
          onCommit(parsed);
        }}
        onChange={(event) =>
          setDraft(sanitizeScoreExpressionInput(event.target.value))
        }
        onKeyDown={(event) => {
          if (event.key === "Enter") {
            event.currentTarget.blur();
          }

          if (event.key === "Escape") {
            setDraft(formatGroupedScoreInput(value));
            event.currentTarget.blur();
          }
        }}
        placeholder="--"
        type="text"
        variant="inline-number"
        value={draft}
      />
      {draft.trim() !== "" && !draft.includes("/") ? (
        <span className="pointer-events-none absolute right-1 top-1/2 -translate-y-1/2 text-sm text-ink-subtle">
          %
        </span>
      ) : null}
    </div>
  );
}

function parseGroupedScoreInput(value: string) {
  const normalized = value.trim();
  if (normalized === "") {
    return null;
  }

  if (normalized.includes("/")) {
    const [left, right] = normalized
      .split("/")
      .map((part) => Number(part.trim()));

    if (Number.isFinite(left) && Number.isFinite(right) && right > 0) {
      return roundGroupedScore((left / right) * 100);
    }

    return null;
  }

  const numeric = Number(normalized.replace("%", "").trim());
  if (!Number.isFinite(numeric)) {
    return null;
  }

  return roundGroupedScore(numeric);
}

function formatGroupedScoreInput(value: number | null) {
  if (value === null) {
    return "";
  }

  return Number.isInteger(value) ? String(value) : String(value);
}

function roundGroupedScore(value: number) {
  const normalized = Math.max(value, 0);
  return Math.round(normalized * 10) / 10;
}
