import { Semester } from "@/lib/types";

export const demoSemester: Semester = {
  id: "semester-1",
  name: "Autumn Semester",
  periodLabel: "February 3 to June 21",
  targetAverage: 78,
  courses: [
    {
      id: "course-human-computer-interaction",
      code: "INF304",
      name: "Human-Computer Interaction",
      instructor: "Dr. Elaine Mercer",
      credits: 16,
      accent: "from-stone-950 via-stone-900 to-zinc-800",
      assessments: [
        {
          id: "hci-research-brief",
          name: "Research Brief",
          weight: 15,
          scoreAchieved: 86,
          totalPossible: 100,
          dueDate: "Mar 04",
          category: "assignment",
          status: "completed",
        },
        {
          id: "hci-usability-audit",
          name: "Usability Audit",
          weight: 20,
          scoreAchieved: 73,
          totalPossible: 100,
          dueDate: "Mar 19",
          category: "project",
          status: "completed",
        },
        {
          id: "hci-prototype-crit",
          name: "Prototype Crit",
          weight: 25,
          scoreAchieved: null,
          totalPossible: 100,
          dueDate: "Apr 11",
          category: "presentation",
          status: "ongoing",
        },
        {
          id: "hci-final-report",
          name: "Final Design Report",
          weight: 40,
          scoreAchieved: null,
          totalPossible: 100,
          dueDate: "May 27",
          category: "exam",
          status: "ongoing",
        },
      ],
    },
    {
      id: "course-data-analytics",
      code: "STA228",
      name: "Applied Data Analytics",
      instructor: "Prof. Jonah Reid",
      credits: 12,
      accent: "from-slate-900 via-slate-800 to-neutral-800",
      assessments: [
        {
          id: "analytics-quiz-1",
          name: "Methods Quiz",
          weight: 10,
          scoreAchieved: 92,
          totalPossible: 100,
          dueDate: "Feb 21",
          category: "quiz",
          status: "completed",
        },
        {
          id: "analytics-lab",
          name: "Data Lab",
          weight: 20,
          scoreAchieved: 81,
          totalPossible: 100,
          dueDate: "Mar 12",
          category: "assignment",
          status: "completed",
        },
        {
          id: "analytics-case-study",
          name: "Case Study",
          weight: 25,
          scoreAchieved: 78,
          totalPossible: 100,
          dueDate: "Apr 02",
          category: "project",
          status: "completed",
        },
        {
          id: "analytics-final",
          name: "Final Examination",
          weight: 45,
          scoreAchieved: null,
          totalPossible: 100,
          dueDate: "Jun 06",
          category: "exam",
          status: "ongoing",
        },
      ],
    },
    {
      id: "course-systems-design",
      code: "CSC312",
      name: "Systems Design Studio",
      instructor: "Ava Nakamura",
      credits: 14,
      accent: "from-neutral-900 via-stone-800 to-stone-700",
      assessments: [
        {
          id: "systems-sprint-1",
          name: "Sprint Review I",
          weight: 15,
          scoreAchieved: 88,
          totalPossible: 100,
          dueDate: "Feb 28",
          category: "presentation",
          status: "completed",
        },
        {
          id: "systems-architecture-doc",
          name: "Architecture Dossier",
          weight: 25,
          scoreAchieved: 84,
          totalPossible: 100,
          dueDate: "Mar 25",
          category: "project",
          status: "completed",
        },
        {
          id: "systems-sprint-2",
          name: "Sprint Review II",
          weight: 20,
          scoreAchieved: null,
          totalPossible: 100,
          dueDate: "Apr 22",
          category: "presentation",
          status: "ongoing",
        },
        {
          id: "systems-studio-final",
          name: "Studio Final",
          weight: 40,
          scoreAchieved: null,
          totalPossible: 100,
          dueDate: "May 30",
          category: "exam",
          status: "ongoing",
        },
      ],
    },
  ],
};
